version: "3.7"

services:
    alice:

        image: cybersecuriteachg2/arp_alice
        container_name: mitm_alice
        restart: always

        ports:
            - "5800:5800"
        networks:
            - mitm
    bob:

        image: cybersecuriteachg2/arp_bob
        container_name: mitm_bob
        restart: always
        networks:
            - mitm


    eve:
        privileged: true
        image: cybersecuriteachg2/arp_eve
        container_name: mitm_eve
        sysctls:
            # Necessary for transparent mode for mitmproxy
            - net.ipv4.ip_forward=1
            - net.ipv6.conf.all.forwarding=1
            - net.ipv4.conf.all.send_redirects=0
        networks:
            - mitm

networks:
    mitm:
