version: "3.7"

services:
  tuto_053-syd-academy-billcipher:
    container_name: tuto_053-syd-academy-billcipher
    image: sydacademy/tuto_053-syd-academy-billcipher
    stdin_open: true
    tty: true   
    restart: unless-stopped
