version : '3.7'

services :
  postfixandroundcube :
    image : cybersecuriteachg2/tuto_gophish
    container_name : postfixandroundcube
    restart : unless-stopped
    ports :
      - "25:25"
      - "80:80"
      - "110:110"
      - "143:143"
      - "465:465"
      - "993:993"
      - "995:995"
    networks:
      network1:
        ipv4_address: 172.20.0.2

  gophish :
    image : cybersecuriteachg2/tuto_gophish_outil
    container_name : gophish
    restart : unless-stopped
    ports :
      - "3333:3333"
      - "8080:80"
      - "443:443"
    networks:
      network1:
        ipv4_address: 172.20.0.3

networks:
  network1:
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16