version: "3.7"

services:
    web:
        image: jlesage/firefox
        container_name: web_firefox
        restart: always
        volumes:
            - /dev/shm:/dev/shm
        ports:
            - "5801:5800"
        networks:
            - reseau
    ubuntu:
        build: ./.
        container_name: ubuntu
        restart: always
        networks:
            - reseau
    apache:
        build: ./Serveur-web/.
        container_name: apache
        restart: always
        volumes:
          - ./Serveur-web/Serveur-files:/var/www/html
        networks:
            - reseau

networks:
    reseau: