version: "3.7"

services:
    alice:
        build: ./Alice/.
        image: scapy_alice
        container_name: scapy_alice
        restart: always
        volumes:
            - ./Alice/request.py:/usr/src/app/request.py
        networks:
            - scapy

      
    bob:
        build : ./Bob/.
        
        container_name: scapy_bob
        restart: always
        networks:
            - scapy
    


    eve:
        privileged: true
        build: ./Eve/.
        
        container_name: scapy_eve
        restart: always
        networks:
            - scapy

networks:
    scapy:
        driver: bridge
        
            
        

      
