version: "3.7"

services:

    web:
        image: jlesage/firefox
        container_name: web
        restart: always
        volumes:
            - /dev/shm:/dev/shm
        ports:
            - "5800:5800"
        networks:
            - mitm

    php:
        image: cybersecuriteachg2/sql_php
        container_name: sqlphp
        restart: always

        networks:
            - mitm
            - db
        ports:
          - "3001:80"
    db:
        container_name: db
        image: cybersecuriteachg2/sql_db
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: MYSQL_ROOT_PASSWORD
            MYSQL_DATABASE: MYSQL_DATABASE
            MYSQL_USER: MYSQL_USER
            MYSQL_PASSWORD: MYSQL_PASSWORD
        networks:
            - db

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - '8080:80'
        restart: always
        environment:
            PMA_HOST : db
        depends_on:
            - db
        networks :
            - db
    kali:
        image: cybersecuriteachg2/sql_kali
        container_name: kali
        restart: always
        networks:
            - mitm

        
            



networks:
    mitm:
    db:
