version: "3.7"

services:


    kali:
        image: cybersecuriteachg2/sql_kali
        container_name: kali
        restart: always
        networks:
            - mitm
    shop:
        image: bkimminich/juice-shop
        container_name: shop
        restart: always
        networks: 
            - mitm
        ports:
            - "3000:3000"
        
            



networks:
    mitm:

