services:                                                                                                             │
  commix:                                                                                                             │
    image: picicato/commix:latest                                                                                │
    container_name: commix                                                                                            │
    hostname: commix                                                                                                  │
    stdin_open: true                                                                                                  │
    tty: true
    networks:
      commix:
        ipv4_address: 192.168.60.2                                                                                                         │
  php_commix:                                                                                                         │
    container_name: php_commix                                                                                        │
    image: picicato/php-commix:latest
    networks:
      commix:
        ipv4_address: 192.168.60.3                                                                            │
    ports:                                                                                                            │
      - 5000:80
networks:
  commix:
    driver: bridge
    ipam:
     config:
       - subnet: 192.168.60.0/24                                                                                    │
version: "3.7"
