networks:
  commix:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.60.0/24
services:
  commix:
    container_name: commix
    hostname: commix
    image: picicato/commix:latest
    networks:
      commix:
        ipv4_address: 192.168.60.2
    stdin_open: true
    tty: true
  php_commix:
    container_name: php_commix
    image: picicato/php-commix:latest
    networks:
      commix:
        ipv4_address: 192.168.60.3
    ports:
      - 5000:80
version: '3.7'
