services:
  commix:
    image: picicato/tuto-commix:latest
    container_name: commix
    hostname: commix
    stdin_open: true
    tty: true
    networks:
      commix:
        ipv4_address: 192.168.50.2
  php_commix:
    container_name: php_commix
    image: picicato/tuto-php-commix:latest
    networks:
      commix:
        ipv4_address: 192.168.50.3
    ports:
      - 5000:80
networks:
  commix:
    driver: bridge
    ipam:
     config:
      - subnet: 192.168.50.0/24
version: "3.7"
