version : '3.7'

services :
  postfixandroundcube :
    image : marooou/postfix-roundcube
    container_name : postfixandroundcube
    restart : unless-stopped
    ports :
      - "25:25"
      - "80:80"
      - "110:110"
      - "143:143"
      - "465:465"
      - "993:993"
      - "995:995"
    volumes :
      - /data/mysql:/var/lib/mysql
      - /data/vmail/:/var/vmail
      - /data/log:/var/log
    environment :
      - ADMIN_USERNAME=root
      - ADMIN_PASSWD=password
      - DOMAIN_NAME=example.com
      - USERS=attaquant:azerty12,victime:azerty12

  gophish:
    image: gophish/gophish:latest
    container_name: gophish
    restart : unless-stopped
    ports:
      - "3333:3333"
      - "8080:80"
      - "443:443"
