services:
  msf_machine:
    container_name: msf_machine
    image: chasepd/msfconsole
    stdin_open: true
    tty: true
    restart: always
    networks:
      pdf_reverse_network:
        ipv4_address: 10.5.0.2

networks:
  pdf_reverse_network:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/16
         gateway: 10.5.0.1
