version: "3.7"

services: 
  server:

    image: cybersecuriteachg2/server_sshchall
    container_name: server
    restart: always
    networks: 
      - "SSH_Net"
  kali:
    image: cybersecuriteachg2/sshkalichall
    container_name: kali
    command: tail -F anything
    
    networks:
      - "SSH_Net"

networks:
  SSH_Net: